
type Weight  {
  date: Date!
  weight: Float!
  user: User!
}

type User {
  userId: String! @unique(index: "findUserByUserId")
  name: String!
  initialWeight: Float
  currentWeight: Float
  weights: [Weight!] @relation
}

type Leaderboard @embedded {
  data: [LeaderboardEntry!]
}

type LeaderboardEntry @embedded {
  percentage: Float!,
  userId: String!,
  name: String,
  ref: ID!
}

type Query {
  findUserByUserId(userId: String!): User
  allUsers: [User!] @index(name: "allUsers")
  leaderboard(size: Int = 10): Leaderboard @resolver(name: "leaderboard")
}

