[build]
  command = "npm run build"
  functions = "functions/"
  publish = "build/"

[dev]
	publish = "build/"
  functions = "functions"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  